---
base16_fzf:
  themes:
    alt: base16-mexico-light
    default: base16-helios
base16_shell:
  themes:
    alt: base16_mexico-light
    default: base16_helios
bat:
  style: header,numbers
exercism:
  config:
    token: 3dd7e081-f84a-49ec-98d0-087b8b74807b
    workspace: Organisations/nomas_prime/exercism
fzf:
  alt_c_command: fd --type d --exclude .git --follow --hidden
  alt_c_opts: --preview 'tree -C {} | head -200'
  bindkey_cd_widget: ^[^fc
  bindkey_file_widget: ^[^ff
  bindkey_history_widget: ^[^fr
  clobber_history_incremental_pattern_search_backward: true
  default_command: &default_command fd --type f --exclude .git --follow --hidden
  ctrl_t_command: *default_command
  ctrl_t_opts: --preview '(bat --color=always {} 2> /dev/null || cat {} || tree -C {}) 2> /dev/null | head -200'
  default_opts: --inline-info --layout=reverse --preview-window='66%'
  other_opts: |
    _fzf_compgen_path() {
      fd --exclude ".git" --follow --hidden . "$1"
    }

    _fzf_compgen_dir() {
      fd --exclude ".git" --follow --hidden --type d . "$1"
    }
git:
  config:
    core:
      editor: nvim
    user:
      name: Richard Jones
      email: richard.jones@playtimestudios.com
github:
  user: nomasprime
