---
- hosts: ideos
  roles:
    - brew
    - asdf
    - git
    - github
    - codex

- hosts: human_workstations
  roles:
    - base16-fzf
    - base16-shell
    - direnv
    - docker
    - exercism
    - flutter
    - fzf
    - gnupg
    - iterm
    - karabiner
    - macos-trash
    - neovim
    - ngrok
    - openssl
    - overmind
    - prezto
    - tmux
    - tmuxinator

- hosts: agent_workstations
  roles:
    - macos-power
