---
- name: install zsh
  homebrew:
    name: zsh
    state: present

- name: install coreutils
  homebrew:
    name: coreutils
    state: present

- name: enable zsh
  become: true
  lineinfile:
    line: "{{ brew['prefix'] }}/bin/zsh"
    path: /etc/shells

- name: test shell
  command: "dscl localhost -read /Local/Default/Users/{{ ansible_user_id }} shell"
  register: test_shell_result

- name: change shell
  become: true
  command: "chsh -s {{ brew['prefix'] }}/bin/zsh {{ ansible_user_id }}"
  when:
    - test_shell_result.stdout.find('/usr/local/bin/zsh') == -1
