---
- include: darwin.yml
  when: ansible_os_family == 'Darwin'

- include: debian.yml
  when: ansible_os_family == 'Debian'

- name: clone repository
  git:
    dest: ~/.zprezto
    recursive: yes
    repo: git@github.com:{{ git['github']['username'] }}/prezto.git
    update: no

- name: add runcoms
  blockinfile:
    block: "{{ lookup('file', '~/.zprezto/runcoms/' + item) }}"
    create: yes
    insertbefore: BOF
    marker: "# {mark} {{ role_path|basename }} add runcoms"
    path: "~/.{{ item }}"
  with_items:
    - zlogin
    - zlogout
    - zpreztorc
    - zprofile
    - zshenv
    - zshrc
