---
- name: install asdf
  homebrew:
    name: asdf
    state: present

- name: add config to rc
  blockinfile:
    block: source {{ brew['prefix'] }}/opt/asdf/asdf.sh
    marker: "# {mark} {{ role_path|basename }} add config to rc"
    path: ~/.zshrc

- name: manage config
  template:
    dest: ~/.asdfrc
    src: .asdfrc.j2

- name: install plugins
  shell: asdf plugin add {{ item.name }}
  args:
    creates: "~/.asdf/plugins/{{ item.name }}"
  with_items: "{{ asdf['globals'] }}"

- name: global versions
  shell: cat ~/.tool-versions
  register: global_versions

- name: install latest versions
  shell: asdf install {{ item.name }} latest
  with_items:
    - "{{ asdf['globals'] }}"
  when:
    - item.version is not defined
    - global_versions.stdout.find(item.name) == -1

- name: install specific versions
  shell: asdf install {{ item.name }} {{ item.version }}
  args:
    creates: "~/.asdf/installs/{{ item.name }}/{{ item.version }}"
  with_items:
    - "{{ asdf['globals'] }}"
  when: item.version is defined

- name: set global to latest versions
  shell: asdf global {{ item.name }} latest
  with_items:
    - "{{ asdf['globals'] }}"
  when:
    - item.version is not defined
    - global_versions.stdout.find(item.name) == -1
