---
- name: install homebrew
  shell: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  args:
    creates: "{{ brew['prefix'] }}/Homebrew"
    executable: /bin/bash
