---
- name: OS vars
  include_vars: "{{ ansible_os_family|lower }}.yml"

- include_tasks: darwin.yml
  when: ansible_os_family == 'Darwin'

- include_tasks: debian.yml
  when: ansible_os_family == 'Debian'
