---
- name: install packages
  homebrew:
    name:
      - fd
      - fzf
      - tree
    state: present

- name: manage config directory
  file:
    path: ~/.fzf
    state: directory

- name: add config to rc
  blockinfile:
    block: "[ -f ~/.fzf/init.{{ item }} ] && source ~/.fzf/init.{{ item }}"
    marker: "# {mark} {{ role_path|basename }} add config to rc"
    path: ~/.{{ item }}rc
  with_items:
    - bash
    - zsh

- name: config
  template:
    dest: ~/.fzf/init.{{ item }}
    src: init.j2
  with_items:
    - bash
    - zsh

- name: key bindings config
  template:
    dest: ~/.fzf/key-bindings.zsh
    src: key-bindings.zsh.j2
