---
- name: install git
  homebrew:
    name: git
    state: present

- name: manage config
  blockinfile:
    block: "{{ lookup('template', 'templates/.gitconfig.j2') }}"
    create: yes
    marker: "# {mark} {{ role_path|basename }} manage config"
    path: ~/.gitconfig

- name: manage ignore
  template:
    dest: ~/.gitignore
    src: .gitignore.j2
