---
- name: install packages
  homebrew:
    name:
      - bfg
      - git
    state: present

- name: install git-wip
  get_url:
    dest: "{{ brew['prefix'] }}/bin"
    mode: 0755
    url: https://raw.githubusercontent.com/nomasprime/git_wip/master/git-wip

- name: manage config
  blockinfile:
    block: "{{ lookup('template', 'templates/.gitconfig.j2') }}"
    create: yes
    marker: "# {mark} {{ role_path|basename }} manage config"
    path: ~/.gitconfig

- name: manage ignore
  template:
    dest: ~/.gitignore
    src: .gitignore.j2
