---
- name: install git
  homebrew:
    name: git
    state: present

- name: manage config
  template:
    dest: ~/.gitconfig
    src: .gitconfig.j2

- name: manage ignore
  template:
    dest: ~/.gitignore
    src: .gitignore.j2

- name: add github to known hosts
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.ssh/known_hosts"
    create: yes
    state: present
    line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
    regexp: "^github\\.com"
