---
- name: clone repository
  git:
    dest: ~/.config/base16-shell
    recursive: yes
    repo: git@github.com:chriskempson/base16-shell.git
    update: no

- name: add config to rc
  blockinfile:
    block: |
      BASE16_SHELL="$HOME/.config/base16-shell"
      [ -n "$PS1" ] && [ -s $BASE16_SHELL/profile_helper.sh ] && eval "$($BASE16_SHELL/profile_helper.sh)"

      if [ $ITERM_PROFILE = "Alt" ]; then
        {{ base16_shell['themes']['alt'] }}
      else
        {{ base16_shell['themes']['default'] }}
      fi
    create: yes
    marker: "# {mark} {{ role_path|basename }} add config to rc"
    path: ~/.{{ item }}rc
  with_items:
    - bash
    - zsh
