---
- name: install ctags
  homebrew:
    name: ctags
    state: present

- name: install neovim
  homebrew:
    install_options: --HEAD
    name: neovim
    state: present

- name: install node provider
  npm:
    name: neovim
    global: true
    state: present

- name: install python 3 provider
  pip:
    executable: pip3
    name: neovim
    state: present

- name: install ruby provider
  gem:
    name: neovim
    state: present
    user_install: no

- name: install rg
  homebrew:
    name: rg
    state: present

- name: manage config directories
  file:
    path: ~/.config/nvim/{{ item.path }}
    state: directory
  when: item.state == 'directory'
  with_filetree: templates/nvim

- name: manage config files
  template:
    dest: ~/.config/nvim/{{ item.path }}
    force: yes
    src: "{{ item.src }}"
  register: config
  with_filetree: templates/nvim
  when: item.state == 'file'

- name: download vim plug
  command: curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  args:
    creates: "{{ ansible_env.HOME }}/.config/nvim/autoload/plug.vim"

- name: install vim plug plugins
  expect:
    command: "{{ brew['prefix'] }}/bin/nvim --headless +PlugInstall +qa && {{ brew['prefix'] }}/bin/nvim --headless +PlugClean +y +qa"
    responses:
      Delete all directories\? \(y/N\): "y\n"
  ignore_errors: true
  when: config.changed

- name: install python-language-server
  pip:
    executable: pip3
    name: python-language-server
    state: present

- name: install flake8
  pip:
    executable: pip3
    name: flake8
    state: present

- name: install mypy
  pip:
    executable: pip3
    name: mypy
    state: present

- name: install eslint
  npm:
    name: "{{item}}"
    path: ~/
    state: present
  with_items:
    - eslint
    - eslint-config-airbnb
    - eslint-plugin-import
    - eslint-plugin-react
    - eslint-plugin-react-hooks
    - eslint-plugin-jsx-a11y

- name: manage eslint config
  copy:
    dest: ~/.eslintrc
    force: yes
    src: .eslintrc

- name: install jest-vim-reporter
  npm:
    name: jest-vim-reporter
    path: ~/
    state: present
