# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/zesty64"
  config.vm.network "private_network", ip: "192.168.33.10"

  config.vm.provider :virtualbox do |vb|
    vb.gui = {{ pillar.dvm.vagrantfile.gui }}
    vb.memory = {{ pillar.dvm.vagrantfile.memory }}
    vb.cpus = {{ pillar.dvm.vagrantfile.cpus }}
  end

  config.vm.synced_folder ".", "/vagrant", :disabled => true

  config.vm.synced_folder ENV['HOME'], "{{ pillar.dvm.vagrantfile.synced_folder }}", :id => "home", :nfs => true, :mount_options => ['nolock,vers=3,udp']

  config.vm.provision "shell", :path => "../../bin/bootstrap", :privileged => false
  config.vm.provision "shell", :path => "bin/bootstrap", :privileged => false
end
